# Generated by Django 5.1.15 on 2026-08-16 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('hostels', '0002_studentprofile_nic_back_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_users', to='hostels.hostel'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('CITY_MANAGER', 'City Manager'), ('HOSTEL_MANAGER', 'Hostel Manager'), ('PARTNER', 'Partner'), ('STAFF', 'Staff'), ('STUDENT', 'Student')], default='STUDENT', max_length=20),
        ),
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('SUPER_ADMIN', 'Super Admin'), ('CITY_MANAGER', 'City Manager'), ('HOSTEL_MANAGER', 'Hostel Manager'), ('PARTNER', 'Partner'), ('STAFF', 'Staff'), ('STUDENT', 'Student')], max_length=20, null=True)),
                ('module_name', models.CharField(max_length=50)),
                ('can_view', models.BooleanField(default=False)),
                ('can_add', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('role', 'module_name'), name='unique_role_module'), models.UniqueConstraint(condition=models.Q(('role__isnull', True)), fields=('user', 'module_name'), name='unique_user_module')],
            },
        ),
    ]
