# Generated by Django 5.2.8 on 2025-11-18 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Pakistan', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='hostels.building')),
            ],
            options={
                'unique_together': {('building', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hostels', to='hostels.city')),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='hostels.hostel'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('room_type', models.CharField(choices=[('SINGLE', 'Single'), ('DOUBLE', 'Double'), ('TRIPLE', 'Triple'), ('OTHER', 'Other')], default='TRIPLE', max_length=20)),
                ('is_ac', models.BooleanField(default=False)),
                ('base_rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hostels.floor')),
            ],
            options={
                'unique_together': {('floor', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=10)),
                ('is_occupied', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='hostels.room')),
            ],
            options={
                'unique_together': {('room', 'label')},
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('guardian_name', models.CharField(blank=True, max_length=100)),
                ('guardian_phone', models.CharField(blank=True, max_length=20)),
                ('college_name', models.CharField(blank=True, max_length=150)),
                ('course', models.CharField(blank=True, max_length=150)),
                ('year', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_on', models.DateField(blank=True, null=True)),
                ('left_on', models.DateField(blank=True, null=True)),
                ('bed', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student', to='hostels.bed')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='hostels.hostel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='building',
            unique_together={('hostel', 'name')},
        ),
    ]
