# Generated by Django 5.1.15 on 2026-08-16 20:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


def backfill_missing_joined_on(apps, schema_editor):
    StudentProfile = apps.get_model('hostels', 'StudentProfile')
    today = datetime.date.today()
    StudentProfile.objects.filter(joined_on__isnull=True).update(joined_on=today)


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0002_alter_studentprofile_hostel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='nic_back_picture',
            field=models.ImageField(blank=True, null=True, upload_to='student/nic_back/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='nic_front_picture',
            field=models.ImageField(blank=True, null=True, upload_to='student/nic_front/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='nic_number',
            field=models.CharField(default='UNKNOWN', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='student/profile/'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='college_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='guardian_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='guardian_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='whatsapp',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='StudentUtilityCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilities', to='hostels.studentprofile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
