# Generated by Django 5.1.15 on 2026-07-01 02:18:17.898438

import datetime
import django.db.models.deletion
from django.db import migrations, models


def backfill_missing_joined_on(apps, schema_editor):
    StudentProfile = apps.get_model('hostels', 'StudentProfile')
    today = datetime.date.today()
    StudentProfile.objects.filter(joined_on__isnull=True).update(joined_on=today)


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='hostels.hostel'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='joined_on',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.RunPython(backfill_missing_joined_on, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='studentprofile',
            name='joined_on',
            field=models.DateField(),
        ),
    ]
