# Generated by Django 5.1.15 on 2026-07-02 22:16:45.494707

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0002_studentprofile_nic_back_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='parent_phone',
            field=models.CharField(default='UNKNOWN', help_text='For automated fee alerts', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='parent_whatsapp',
            field=models.CharField(default='UNKNOWN', help_text='For automated receipts', max_length=20),
            preserve_default=False,
        ),
    ]
