# Generated by Django 5.1.15 on 2026-07-02 22:36:37.128326

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0003_studentprofile_parent_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='parent_link_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
