# Generated by Django 5.1.15 on 2026-08-18 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0005_studentprofile_guardian_nic_parent_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='monthly_rent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
