# Generated by Django 5.1.15 on 2026-09-08 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_properties(apps, schema_editor):
    Property = apps.get_model("hostels", "Property")
    Building = apps.get_model("hostels", "Building")

    for building in Building.objects.filter(property__isnull=True).iterator():
        property_obj = Property.objects.create(
            hostel_id=building.hostel_id,
            name=building.name,
            code=f"LEGACY-BLD-{building.pk}",
            property_type="BUILDING",
        )
        Building.objects.filter(pk=building.pk).update(property_id=property_obj.pk)


def reverse_properties(apps, schema_editor):
    Property = apps.get_model("hostels", "Property")
    Building = apps.get_model("hostels", "Building")
    Building.objects.filter(property__code__startswith="LEGACY-BLD-").update(property=None)
    Property.objects.filter(code__startswith="LEGACY-BLD-").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0006_studentprofile_monthly_rent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=30)),
                ('property_type', models.CharField(choices=[('HOUSE', 'House'), ('APARTMENT', 'Apartment'), ('BUILDING', 'Standalone Building')], default='BUILDING', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='hostels.hostel')),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buildings', to='hostels.property'),
        ),
        migrations.RunPython(backfill_properties, reverse_properties),
        migrations.CreateModel(
            name='BedAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_in_date', models.DateField()),
                ('move_out_date', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='hostels.bed')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bed_allocations', to=settings.AUTH_USER_MODEL)),
                ('previous_bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to='hostels.bed')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bed_allocations', to='hostels.studentprofile')),
            ],
            options={
                'ordering': ['-move_in_date', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('student',), name='one_active_bed_allocation_per_student'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('bed',), name='one_active_bed_allocation_per_bed')],
            },
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.UniqueConstraint(fields=('hostel', 'code'), name='unique_property_code_per_hostel'),
        ),
    ]
