# Generated by Django 5.1.15 on 2026-08-16 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_add_missing_asset_fields'),
        ('hostels', '0002_studentprofile_nic_back_picture_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='current_value',
            field=models.DecimalField(decimal_places=2, help_text='Book value after depreciation', max_digits=12),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active & In Use'), ('MAINTENANCE', 'Under Repair'), ('SOLD', 'Sold / Disposed'), ('SCRAPPED', 'Scrapped / Damaged')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='depreciation_rate_annual',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Percentage value (0-100)', max_digits=5),
        ),
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('LOAN', 'Long-term Loan'), ('CREDIT', 'Vendor Credit / Payable'), ('OTHER', 'Other Liability')], default='CREDIT', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_settled', models.BooleanField(default=False)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liabilities', to='hostels.hostel')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerCapital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_invested', models.DateField()),
                ('remarks', models.TextField(blank=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capital_investments', to='hostels.hostel')),
                ('partner', models.ForeignKey(limit_choices_to={'role': 'PARTNER'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
