# Generated by Django 5.1.15 on 2026-09-08 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_asset_current_value_alter_asset_status_and_more'),
        ('hostels', '0008_backfill_bed_allocations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='hostels.property'),
        ),
        migrations.AddField(
            model_name='liability',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liabilities', to='hostels.property'),
        ),
        migrations.AddField(
            model_name='partnercapital',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capital_investments', to='hostels.property'),
        ),
        migrations.CreateModel(
            name='PropertyRentalContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landlord_name', models.CharField(max_length=200)),
                ('landlord_contact', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=15)),
                ('landlord_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_contracts', to='hostels.property')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='InvestorPropertyAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_financials', models.BooleanField(default=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_access', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investor_access', to='hostels.property')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('investor', 'property'), name='unique_investor_property_access')],
            },
        ),
        migrations.CreateModel(
            name='InvestorPropertyOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_ownerships', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investor_ownerships', to='hostels.property')),
            ],
            options={
                'ordering': ['property', '-effective_from'],
                'constraints': [models.UniqueConstraint(fields=('investor', 'property', 'effective_from'), name='unique_investor_property_ownership_period')],
            },
        ),
        migrations.CreateModel(
            name='PropertyRentAccrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the accrued month')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rent_accruals', to='hostels.property')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accruals', to='finance.propertyrentalcontract')),
            ],
            options={
                'ordering': ['-month'],
                'constraints': [models.UniqueConstraint(fields=('property', 'contract', 'month'), name='unique_property_rent_accrual_month')],
            },
        ),
    ]
