# Generated by Django 5.1.15 on 2026-09-08 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_asset_property_liability_property_and_more'),
        ('hostels', '0008_backfill_bed_allocations'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertySharedCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField(blank=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shared_costs', to='hostels.hostel')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shared_costs', to='hostels.property')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
