# Generated by Django 5.1.15 on 2026-08-16 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0002_studentprofile_nic_back_picture_and_more'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='reorder_level',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Alert when stock falls below this', max_digits=12),
        ),
        migrations.AddField(
            model_name='purchase',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchase',
            name='invoice_photo',
            field=models.ImageField(blank=True, null=True, upload_to='inventory/purchases/invoices/'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='items_photo',
            field=models.ImageField(blank=True, null=True, upload_to='inventory/purchases/items/'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='rejection_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='inventory/consumptions/')),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='hostels.hostel')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='inventory.item')),
            ],
        ),
    ]
