# Generated by Django 5.1.15 on 2026-09-08 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0008_backfill_bed_allocations'),
        ('inventory', '0002_item_reorder_level_purchase_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumption',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='hostels.property'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='hostels.property'),
        ),
    ]
