# Generated by Django 5.1.15 on 2026-08-24 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groceryrequirement',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='groceryrequirement',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mealrecipe',
            name='waste_factor',
            field=models.DecimalField(decimal_places=2, default=0.05, help_text='Waste percentage (e.g., 0.05 for 5%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='weeklymenutemplate',
            name='friday_breakfast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fri_breakfast', to='food.meal'),
        ),
        migrations.AddField(
            model_name='weeklymenutemplate',
            name='friday_dinner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fri_dinner', to='food.meal'),
        ),
        migrations.AddField(
            model_name='weeklymenutemplate',
            name='friday_lunch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fri_lunch', to='food.meal'),
        ),
        migrations.AddField(
            model_name='weeklymenutemplate',
            name='saturday_breakfast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sat_breakfast', to='food.meal'),
        ),
        migrations.AddField(
            model_name='weeklymenutemplate',
            name='saturday_dinner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sat_dinner', to='food.meal'),
        ),
        migrations.AddField(
            model_name='weeklymenutemplate',
            name='saturday_lunch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sat_lunch', to='food.meal'),
        ),
        migrations.AddField(
            model_name='weeklymenutemplate',
            name='sunday_breakfast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sun_breakfast', to='food.meal'),
        ),
        migrations.AddField(
            model_name='weeklymenutemplate',
            name='sunday_dinner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sun_dinner', to='food.meal'),
        ),
        migrations.AddField(
            model_name='weeklymenutemplate',
            name='sunday_lunch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sun_lunch', to='food.meal'),
        ),
        migrations.AddField(
            model_name='weeklymenutemplate',
            name='thursday_breakfast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thu_breakfast', to='food.meal'),
        ),
        migrations.AddField(
            model_name='weeklymenutemplate',
            name='thursday_dinner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thu_dinner', to='food.meal'),
        ),
        migrations.AddField(
            model_name='weeklymenutemplate',
            name='thursday_lunch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thu_lunch', to='food.meal'),
        ),
        migrations.AddField(
            model_name='weeklymenutemplate',
            name='tuesday_breakfast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tue_breakfast', to='food.meal'),
        ),
        migrations.AddField(
            model_name='weeklymenutemplate',
            name='tuesday_dinner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tue_dinner', to='food.meal'),
        ),
        migrations.AddField(
            model_name='weeklymenutemplate',
            name='tuesday_lunch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tue_lunch', to='food.meal'),
        ),
        migrations.AddField(
            model_name='weeklymenutemplate',
            name='wednesday_breakfast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wed_breakfast', to='food.meal'),
        ),
        migrations.AddField(
            model_name='weeklymenutemplate',
            name='wednesday_dinner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wed_dinner', to='food.meal'),
        ),
        migrations.AddField(
            model_name='weeklymenutemplate',
            name='wednesday_lunch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wed_lunch', to='food.meal'),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='special_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mealfeedback',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
