# Generated by Django 5.1.15 on 2026-09-01 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hostels', '0006_studentprofile_monthly_rent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_recurring', models.BooleanField(default=True)),
                ('frequency', models.CharField(default='MONTHLY', max_length=20)),
                ('default_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='FeeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_day', models.PositiveIntegerField(default=4)),
                ('late_fee_type', models.CharField(choices=[('FIXED', 'Fixed'), ('PER_DAY', 'Per Day')], default='FIXED', max_length=20)),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('per_day_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fee_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='fees.feehead')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_partially_paid', models.BooleanField(default=False)),
                ('late_fee_applied', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fee_head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fees.feehead')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='hostels.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'fee_head', 'month')},
            },
        ),
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='payment_proofs/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_proofs', to='fees.monthlyfee')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_issued', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(default='Bank Transfer', max_length=50)),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='fees.monthlyfee')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paid', models.DateField()),
                ('status', models.CharField(choices=[('HELD', 'Held by Hostel'), ('REFUNDED', 'Refunded to Student'), ('FORFEITED', 'Forfeited')], default='HELD', max_length=20)),
                ('refund_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_deposit', to='hostels.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentUtilityBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utility_bills', to='hostels.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'month')},
            },
        ),
    ]
