# Generated by Django 5.2.8 on 2025-11-18 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hostels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_recurring', models.BooleanField(default=True)),
                ('frequency', models.CharField(default='MONTHLY', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FeeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_day', models.PositiveIntegerField(default=5)),
                ('late_fee_type', models.CharField(choices=[('FIXED', 'Fixed'), ('PER_DAY', 'Per Day')], default='FIXED', max_length=20)),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('per_day_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fee_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='fees.feehead')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('late_fee_applied', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fee_head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fees.feehead')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='hostels.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'fee_head', 'month')},
            },
        ),
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='payment_proofs/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_proofs', to='fees.monthlyfee')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
