# Generated by Django 5.1.15 on 2026-09-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyfee',
            name='fine_waived_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='monthlyfee',
            name='fine_was_waived',
            field=models.BooleanField(default=False),
        ),
    ]
