# Generated by Django 5.2.8 on 2025-11-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feehead',
            name='default_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
