# Generated by Django 5.1.15 on 2026-08-16 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_feehead_default_amount'),
        ('hostels', '0002_studentprofile_nic_back_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyfee',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='monthlyfee',
            name='is_partially_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feerule',
            name='due_day',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_issued', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(default='Bank Transfer', max_length=50)),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='fees.monthlyfee')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paid', models.DateField()),
                ('status', models.CharField(choices=[('HELD', 'Held by Hostel'), ('REFUNDED', 'Refunded to Student'), ('FORFEITED', 'Forfeited')], default='HELD', max_length=20)),
                ('refund_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_deposit', to='hostels.studentprofile')),
            ],
        ),
    ]
