# Generated by Django 5.1.15 on 2026-08-16 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('pay_type', models.CharField(choices=[('MONTHLY', 'Fixed Monthly'), ('PER_TASK', 'Paid Per Task/Ticket')], default='MONTHLY', max_length=20)),
                ('nic_number', models.CharField(max_length=30)),
                ('nic_front_picture', models.ImageField(blank=True, null=True, upload_to='employee/nic_front/')),
                ('nic_back_picture', models.ImageField(blank=True, null=True, upload_to='employee/nic_back/')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='employee/profile/')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('housing_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fuel_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rate_per_task', models.DecimalField(decimal_places=2, default=0, help_text='Amount per resolved ticket', max_digits=10)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('iban', models.CharField(blank=True, max_length=34)),
                ('joined_on', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Awaiting Admin Approval'), ('APPROVED', 'Approved (Authorized)'), ('PAID', 'Disbursed'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('total_net_payout', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_given', models.DateField(auto_now_add=True)),
                ('is_deducted', models.BooleanField(default=False, help_text='True if already subtracted from a pay-slip')),
                ('remarks', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='payroll.employeeprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SalarySlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('task_count', models.IntegerField(default=0, help_text='Count of tickets resolved this month')),
                ('task_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, help_text='Total absences/fines', max_digits=12)),
                ('advance_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('receipt_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('is_disbursed', models.BooleanField(default=False)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.employeeprofile')),
                ('payroll_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slips', to='payroll.payrollrecord')),
            ],
        ),
    ]
