# Generated by Django 5.1.15 on 2026-09-08 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0008_backfill_bed_allocations'),
        ('payroll', '0002_employeeprofile_mobile_employeeprofile_whatsapp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='hostels.property'),
        ),
    ]
