# Generated by Django 5.1.15 on 2026-08-25 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('tables', models.JSONField(default=list)),
                ('fields', models.JSONField(default=list)),
                ('filters', models.JSONField(default=list)),
                ('group_by', models.JSONField(default=list)),
                ('sort_by', models.JSONField(default=list)),
                ('date_range', models.JSONField(default=dict)),
                ('distinct', models.BooleanField(default=False)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('schedule_frequency', models.CharField(blank=True, max_length=20, null=True)),
                ('schedule_time', models.TimeField(blank=True, null=True)),
                ('schedule_recipients', models.JSONField(blank=True, default=list)),
                ('is_shared', models.BooleanField(default=False)),
                ('shared_with_roles', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomReportResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='bi.customreport')),
            ],
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('REVENUE', 'Revenue Report'), ('FEE_COLLECTION', 'Fee Collection Report'), ('OCCUPANCY', 'Occupancy Report'), ('INVENTORY', 'Inventory Report'), ('PAYROLL', 'Payroll Summary'), ('MEAL_FEEDBACK', 'Meal Feedback Report'), ('SECURITY_DEPOSIT', 'Security Deposit Report'), ('HOSTEL_PERFORMANCE', 'Hostel Performance'), ('VENDOR_ANALYSIS', 'Vendor Analysis'), ('STOCK_LEVEL', 'Stock Level Report')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('config', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('filters', models.JSONField(default=dict)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to='bi.reporttemplate')),
            ],
        ),
    ]
